package com.example.limsebatchmanagement.Enum;

public enum FieldToUpdate {
    EXPORT_FILE("L"),
    STATUS("K"),
    OFFICIAL_NOTE("M"),
    LAB_NOTE("N"),
    SEMAPHORE("P"),
    ENTRY("G"),
    TEMPORARY("M"),
    DATA_PREP("D"),
    ANALISTA_PREP("E"),
    MATERIALE("F"),
    DESCRIZIONE_DETTAGLIATA("G"),
    TRATTAMENTO("H"),
    SCREENING("I"),
    NOTE_PREP("J"),
    PESO("K"),
    DATA_ANALISI("L"),
    ANALISTA_ANALISI("M"),
    N_CAMPI("N"),
    INGRANDIMENTI("O"),
    FIBRE_RILEVATE("P"),
    TIPOLOGIA_1("Q"),
    TIPOLOGIA_1_MORFOLOGIA("R"),
    TIPOLOGIA_1_ASPECT_RATIO("S"),
    TIPOLOGIA_1_ANALISI_CHIMICA_EDS("T"),
    TIPOLOGIA_1_TIPO_FIBRA("U"),
    TIPOLOGIA_1_N_FIBRE("V"),
    TIPOLOGIA_2("W"),
    TIPOLOGIA_2_MORFOLOGIA("X"),
    TIPOLOGIA_2_ASPECT_RATIO("Y"),
    TIPOLOGIA_2_ANALISI_CHIMICA_EDS("Z"),
    TIPOLOGIA_2_TIPO_FIBRA("AA"),
    TIPOLOGIA_2_N_FIBRE("AB"),
    TIPOLOGIA_3("AC"),
    TIPOLOGIA_3_MORFOLOGIA("AD"),
    TIPOLOGIA_3_ASPECT_RATIO("AE"),
    TIPOLOGIA_3_ANALISI_CHIMICA_EDS("AF"),
    TIPOLOGIA_3_TIPO_FIBRA("AG"),
    TIPOLOGIA_3_N_FIBRE("AH"),
    ESITO_ANALISI_QUALIT("AI"),
    NOTE_ANALISI("AJ"),
    STUB("AK"),
    MATRICE("AL"),
    STRUMENTO("AM"),
    CONTATORE_CAMPI("AN"),
    PESO_ANTE_CALCINAZIONE("AO"),
    PESO_POST_CALCINAZIONE("AP"),
    METODO("AQ"),
    BANDA_VISIBILE("AR"),
    PREP_DONE("AS"),
    ANALYSIS_DONE("AT");
    private String sheetColumn;
    FieldToUpdate(String sheetColumn){this.sheetColumn=sheetColumn;}
    public String getColumn(){return sheetColumn;}
}